apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lam-config
  namespace: ad-ui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi