apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - local-path-storage
  - cert-manager
  - external-secrets
  - vault-or-openbao
  - ingress-or-gateway
  - kubernetes-dashboard
  - postgres
  - object-storage
  - vector-db
  - monitoring
  - policy