apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: kubernetes-dashboard
      namespace: kubernetes-dashboard
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: k8s.prod.w237.local
      - op: replace
        path: /spec/rules/0/host
        value: k8s.prod.w237.local