---
- name: Deploy RKE2 cluster
  hosts: all
  become: true
  vars:
    cluster_rke2_config:
      disable:
        - rke2-ingress-nginx
  roles:
    - role: rke2

  post_tasks:
    - name: Wait for cluster to be ready
      ansible.builtin.pause:
        seconds: 30
      when: inventory_hostname in groups['rke2_servers'][0]

    - name: Get kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: ./kubeconfig
        flat: yes
      when: inventory_hostname in groups['rke2_servers'][0]
